# JEmoji by JoseMarcellio
# set permission to "none" to bypass emoji permission
# bypass global permission "jemoji.*"
# custom head support! head;texture
# set permission to "none" or change price to -1 to disable economy

gui-name: "&8JEmoji GUI"

clear-color-after-emoji: true
clear-color-symbol: "&r"

emoji-chat-suggestion: true
emoji-chat-suggestion-prefix: "@"

close-gui-after-purchase-emoji: true
purchase-message-success: "&7You purchased {emoji} &7for &a{price}"
purchase-message-failed: "&7You need &a{price} &7to purchase {emoji}"
purchase-sound-success: "NOTE_PLING"
purchase-sound-failed: "ENDERMAN_TELEPORT"

emoji:
  "<3":
    icon: "EMERALD"
    set-emoji: "&c❤"
    permission: "jemoji.<3"
    price: 250
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
    executor: "lp user {player} permission set {permission}"
  ":cat:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWY3YjA1NWU2ZmVmOTE0ZGNkMmI4NjJhZGMwMWI4MzM4ZTc5ZTFiMjZhYzNhNzExZjg4ZDE2NzZjNDI4NjgxNSJ9fX0="
    set-emoji: "&e= &b＾● ⋏ ●＾ &e="
    permission: "jemoji.cat"
    price: 500
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
    executor: "lp user {player} permission set {permission}"
  ":yey:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTJlOTgxNjVkZWVmNGVkNjIxOTUzOTIxYzFlZjgxN2RjNjM4YWY3MWMxOTM0YTQyODdiNjlkN2EzMWY2YjgifX19"
    set-emoji: "&aヽ (◕◡◕) ﾉ"
    permission: "jemoji.yey"
    price: 500
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
    executor: "lp user {player} permission set {permission}"
  ":puffer:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjkyMzUwYzlmMDk5M2VkNTRkYjJjNzExMzkzNjMyNTY4M2ZmYzIwMTA0YTliNjIyYWE0NTdkMzdlNzA4ZDkzMSJ9fX0="
    set-emoji: "&e<('O')>"
    permission: "jemoji.puffer"
    price: 1000
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
    executor: "lp user {player} permission set {permission}"
  ":dog:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjkzZDFiYzQwNWQ5ZGU2MDA4ZWNjYjI1MzkxZWQ4ZWY4MDllZDViNWRmZmJkMTBjNjQ5YmM4YTQ4YjZlOTFlIn19fQ=="
    set-emoji: "&6(ᵔᴥᵔ)"
    permission: "jemoji.dog"
    price: 1000
    lore:
      - "&7Chat Prefix: &a{prefix}"
      - "&7Permission: &a{permission}"
      - "&7Price: &a{price}"
    executor: "lp user {player} permission set {permission}"