name: JEmoji
main: com.josemarcellio.jemoji.core.JEmoji
author: JoseMarcellio
version: 1.6
description: A lightweight emoji plugin!
softdepend: [Vault, PlaceholderAPI]
commands:
  jemoji:
    aliases: emoji
