# JEmoji by JoseMarcellio
# set permission to "none" to bypass emoji permission
# bypass global permission "jemoji.*"
# custom head support! head;texture

gui-name: "&8JEmoji GUI"

clear-color-after-emoji: true
clear-color-symbol: "&r"

emoji:
  "<3":
    icon: "EMERALD"
    set-emoji: "&c❤"
    permission: "jemoji.<3"
    lore:
      - "&7Chat Prefix: &a<3"
      - "&7Permission: &ajemoji.<3"
  ":cat:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWY3YjA1NWU2ZmVmOTE0ZGNkMmI4NjJhZGMwMWI4MzM4ZTc5ZTFiMjZhYzNhNzExZjg4ZDE2NzZjNDI4NjgxNSJ9fX0="
    set-emoji: "&e= &b＾● ⋏ ●＾ &e="
    permission: "jemoji.cat"
    lore:
      - "&7Chat Prefix: &a:cat:"
      - "&7Permission: &ajemoji.cat"
  ":yey:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTJlOTgxNjVkZWVmNGVkNjIxOTUzOTIxYzFlZjgxN2RjNjM4YWY3MWMxOTM0YTQyODdiNjlkN2EzMWY2YjgifX19"
    set-emoji: "&aヽ (◕◡◕) ﾉ"
    permission: "jemoji.yey"
    lore:
      - "&7Chat Prefix: &a:yey:"
      - "&7Permission: &ajemoji.yey"
  ":puffer:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjkyMzUwYzlmMDk5M2VkNTRkYjJjNzExMzkzNjMyNTY4M2ZmYzIwMTA0YTliNjIyYWE0NTdkMzdlNzA4ZDkzMSJ9fX0="
    set-emoji: "&e<('O')>"
    permission: "jemoji.puffer"
    lore:
      - "&7Chat Prefix: &a:puffer:"
      - "&7Permission: &ajemoji.puffer"
  ":dog:":
    icon: "head;eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjkzZDFiYzQwNWQ5ZGU2MDA4ZWNjYjI1MzkxZWQ4ZWY4MDllZDViNWRmZmJkMTBjNjQ5YmM4YTQ4YjZlOTFlIn19fQ=="
    set-emoji: "&6(ᵔᴥᵔ)"
    permission: "jemoji.dog"
    lore:
      - "&7Chat Prefix: &a:dog:"
      - "&7Permission: &ajemoji.dog"